# Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  labels: 
    app: myapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: canary
  template:
    metadata:
      labels:
        app: myapp
        version: canary
    spec:
      containers:
      - name: myapp
        image: nginx:v2
