apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
      version: stable
  template:
    metadata:
      labels:
        app: tomcat
        version: stable
    spec:
      containers:
      - name: tomcat
        image: tomcat:v1
